---
- name: Converge
  hosts: all
  become: true
  vars:
    foreman_admin_password: testpass1234
    foreman_org_name: test-org
    katello_version: "3.10"
    foreman_version: "1.20"

  roles:
    - role: foreman-server
